name: Gradle test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  parameter-tuner:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-parameter-tuner'
  trajectory-optimization:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-trajectory-optimization'
  math:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-math'
  robotics-tools:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-robotics-tools'
  perception-tools:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-perception-tools'
      requires-self-hosted: true # Needs GPU