name: Gradle test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  gradle-test:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
<<<<<<< HEAD
  parameter-tuner:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-parameter-tuner'
  trajectory-optimization:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'ihmc-trajectory-optimization'
=======
>>>>>>> math/develop
